### ISSUE TITLE
returns no results in bugcrowd

### ISSUE THREAD

**Issue by marz-hunter** [sw33tLie/bbscope#4] opened 2021-01-24 23:33 UTC
```
user@marz:~/h1# bbscope bc -t _crowdcontrol_session=session -b -c url --proxy http://127.0.0.1:8080
user@marz:~/h1#
```

i tried to use the proxy displayed in burp, and the tool runs, but returns no results. what's wrong here?
![VDP](https://user-images.githubusercontent.com/58464282/105647286-71acef00-5e9c-11eb-8a68-08c54d72ad54.PNG)

**Comment by sw33tLie** [comment] 2021-01-26 20:28
Hey there, thanks for raising this issue.
The UI in the picture looks like the old one, and since I've changed the code to work with the new one it's no surprise that's failing now.
Do you see that UI when you're logged in? I was pretty sure that it was still visible when unauthenticated only but I guess I might have been wrong?

**Comment by marz-hunter** [comment] 2021-01-26 23:22
i registered a new bugcrowd account to run the tool, following is the screenshot from bugcrowd, is this the old UI or new? I don't know because I haven't hunted on Bugcrowd for a long time
![accountnew](https://user-images.githubusercontent.com/58464282/105919328-58877800-602d-11eb-94f1-04ce3ffb902e.PNG)

**Comment by marz-hunter** [comment] 2021-01-26 23:23
i run the tool in vps, and tunnel to run the proxy to burp

**Comment by rudrapwn** [comment] 2021-01-27 06:19
It works for me.

Command Used - ```bbscope bc -b -c url -t "MYTOKEN"```

**Comment by sw33tLie** [comment] 2021-01-28 10:09
I spent some more time on this but unfortunately, I can't reproduce it.
@marz-hunter in your case, that's the old UI for sure.
The new UI for the scope table has an `In scope targets` header, like in the picture below
![new-ui](https://user-images.githubusercontent.com/47645560/106122480-0a6f9300-6159-11eb-9ed6-a1b82ef2f99d.png)
I'm fairly sure you could just use [the previous version of this tool](https://github.com/sw33tLie/bbscope/tree/fc6744e6d15b4fb17a10d911ee8f15617e93cee9) for now but it would be nice to figure out why you (and I guess other people) still see that UI :thinking:

**Comment by marz-hunter** [comment] 2021-01-28 10:16
does rendering from burp affect ui? will try again tomorrow and hopefully tool works.

**Comment by marz-hunter** [comment] 2021-01-29 01:21
![noresponse](https://user-images.githubusercontent.com/58464282/106218875-25311e80-61d0-11eb-94e1-305efa648e5d.PNG)
![NOTRESTGSS](https://user-images.githubusercontent.com/58464282/106218888-2cf0c300-61d0-11eb-9504-0267b8ed8b88.PNG)

**Comment by rudrapwn** [comment] 2021-01-29 07:36
I guess you are providing the wrong token here, you shall only provide the token, not the cookie name i.e "crowdcontrol_session".

Hope it works.

**Comment by sw33tLie** [comment] 2021-01-29 14:17
@rudrapwn is right, you don't have to pass the cookie name to the `-t` flag.
Closing this issue now :smiley:

**Closed by sw33tLie** 2021-01-29 14:17 UTC

**Comment by marz-hunter** [comment] 2021-01-29 22:53
somehow it still doesn't work for me, or is there a list of url programs I can get? only public programs in bugcrowd. no problem for hackerone and intigriti.
![nottttttttt](https://user-images.githubusercontent.com/58464282/106335403-a6e28400-6284-11eb-8441-60361185cff4.PNG)
